### ISSUE TITLE
代码运行

### ISSUE THREAD

**Issue by chenchao15** [Greilfang/Our-Red-Alert#5]
请问代码有运行命令吗？想接着修改

**Comment by troysung** [comment]
年代过于久远了，很抱歉我们也没有对这些内容进行记录，请查阅[cocos-2dx User Manual](https://docs.cocos.com/cocos2d-x/manual/zh/)。BTW，我们推荐使用更先进的游戏引擎如UE4, UE5，以及Unity Engine，cocos-2dx社区现已经接近废弃，且引擎优化不佳。
